# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-17 09:52
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiencias_procesos_capacitaciones_formaciones', '0001_initial'),
        ('experiencias_sector_educativos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cursos_capacitaciones_pedagogicos', '0001_initial'),
        ('experiencias_asesorias_acompanamientos_pedagogicos', '0001_initial'),
        ('formaciones_capacitaciones_cargos', '0001_initial'),
        ('experiencias_docentes', '0001_initial'),
        ('experiencias_trabajos_aulas', '0001_initial'),
        ('estudios_realizados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('nombre_host', models.CharField(max_length=255)),
                ('direccion_ip', models.GenericIPAddressField(validators=[django.core.validators.validate_ipv46_address])),
                ('curso_capacitaion_pedagogico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos_capacitaciones_pedagogicos.CursoCapacitacionPedagogico')),
                ('estudio_realizados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudios_realizados.EstudioRealizado')),
                ('experiencia_asesorias_acompanamientos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experiencias_asesorias_acompanamientos_pedagogicos.ExperienciaAsesoriaAcompanamiento')),
                ('experiencia_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experiencias_docentes.ExperienciaDocente')),
                ('experiencia_procesos_capacitaciones_formacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experiencias_procesos_capacitaciones_formaciones.ExperienciaProcesoCapacitacion')),
                ('experiencia_sector_publico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experiencias_sector_educativos.ExperienciaSectorPublico')),
                ('experiencia_trabajo_aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experiencias_trabajos_aulas.ExperienciaTrabajoAula')),
                ('formacion_capacitacion_aspecto_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formaciones_capacitaciones_cargos.FormacionCapacitacionCargo')),
                ('ultimo_usuario_editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_usuario_editor', to=settings.AUTH_USER_MODEL)),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('estudio_realizados',),
                'db_table': 'Evaluaciones',
                'verbose_name': 'Evaluacion',
                'verbose_name_plural': 'Evaluaciones',
            },
        ),
    ]
