# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-10 19:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColeccionPreguntaRespuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('nombre_host', models.CharField(max_length=255)),
                ('direccion_ip', models.GenericIPAddressField(validators=[django.core.validators.validate_ipv46_address])),
            ],
            options={
                'ordering': ('pregunta',),
                'db_table': 'Colecciones_Preguntas_Respuestas',
                'verbose_name': 'Coleccion Pregunta Respuesta',
                'verbose_name_plural': 'Colecciones Preguntas Respuestas',
            },
        ),
    ]
