# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-10 19:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('respuestas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('preguntas', '0001_initial'),
        ('coleccion_preguntas_respuestas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coleccionpreguntarespuesta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preguntas.Pregunta'),
        ),
        migrations.AddField(
            model_name='coleccionpreguntarespuesta',
            name='respuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='respuestas.Respuesta'),
        ),
        migrations.AddField(
            model_name='coleccionpreguntarespuesta',
            name='ultimo_usuario_editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coleccion_pregunta_respuesta_usuario_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coleccionpreguntarespuesta',
            name='usuario_creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
