# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-10 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coleccion_preguntas_respuestas', '0002_auto_20160810_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='coleccionpreguntarespuesta',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
