# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-12 05:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoIdentificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Escribir documento identificaci\xf3n.', max_length=255, unique=True)),
                ('siglas', models.CharField(help_text='Escribir siglas del documento de identificaci\xf3n.', max_length=20)),
                ('numero_digito', models.PositiveSmallIntegerField(default=0, help_text='Escribir el n\xfamero de d\xedgitos del documento de indetificaci\xf3n.')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('nombre_host', models.CharField(max_length=255)),
                ('direccion_ip', models.GenericIPAddressField(validators=[django.core.validators.validate_ipv46_address])),
            ],
            options={
                'ordering': ('id',),
                'db_table': 'Documentos_Identificaciones',
                'verbose_name': 'Documento Identificaci\xf3n',
                'verbose_name_plural': 'Documentos Identificaciones',
            },
        ),
    ]
