# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-12 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, default='default/No-Image-1.png', null=True, upload_to='avatar_usuario'),
        ),
    ]
