# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-21 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0003_auto_20160716_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='activo',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=True),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Escribir descripci\xf3n de la entidad (Opcional).', null=True, verbose_name='Descripci\xf3n'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='documento_identificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos_identificaciones.DocumentoIdentificacion', verbose_name='Documento identificaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='fecha_creacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha creaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='mision',
            field=models.TextField(blank=True, help_text='Escribir misi\xf3n de la entidad (Opcional).', null=True, verbose_name='Misi\xf3n'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='numero_documento_identificacion',
            field=models.CharField(db_index=True, help_text='Escribir n\xfamero documento identificaci\xf3n.', max_length=30, unique=True, verbose_name='N\xfamero documento identificaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='observacion',
            field=models.TextField(blank=True, help_text='Escribir observaci\xf3n de la entidad (Opcional).', null=True, verbose_name='Observaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='vision',
            field=models.TextField(blank=True, help_text='Escribir vision de la entidad (Opcional).', null=True, verbose_name='Visi\xf3n'),
        ),
    ]
