# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-26 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
